spring:
   h2:
      console:
         enabled: true
   jpa:
      show-sql:
        true
      hibernate:
         ddl-auto: create
   datasource:
      url: jdbc:h2:~/mvc-app-qa
      data-username: sa
      data-password:
server:
   port: 8066